### ISSUE TITLE
Librarian-ansible support for git references e.g. tag/branch/SHA or SHA Prefix

### ISSUE THREAD

**Issue by actionjack** [bcoe/librarian-ansible#12]
Hi there I have a feature request is it possible to give support for any
thing that Git will recognize as a ref. This includes any branch name, tag name, SHA, or SHA unique prefix. 

This will allow to do specific version locking when a playbook does not have the version entry in their meta/main.yml file.
Cheers
@actionjack

**Comment by max-b** [comment]
Hey so this is actually already supported, but it could maybe use a little more documentation.

You can do the following:
```
role "maxb.smokeping", git:"https://github.com/max-b/ansible-smokeping.git", ref:"maxb"
```
where the ref could be a branch name or tag name or any valid git reference.

**Comment by bcoe** [comment]
@max-b good suggestion, I'll update the documentation.

Did this do the trick for you @actionjack?

**Comment by actionjack** [comment]
Thanks a lot!
