### ISSUE TITLE
lock file

### ISSUE THREAD

**Issue by Leryan** [bcoe/librarian-ansible#13]
Hi,

The Ansiblefile.lock should'nt be named ".lock". This is confusing with a running process, and this file isn't used that way.

May I suggest ".roleversions" or something like that?

Thanks.

**Comment by bcoe** [comment]
@Leryan librarian-ansible is modeled after Bundler, which uses a file called `Gemfile.lock`. It's using this dependency to do all the heavy lifting, which in turn perpetuates this naming convention.

I definitely understand your point, but I think some of the confusion in the name is mitigated by the fact that this naming convention is standard across `librarian-foo` applications:

https://github.com/applicationsonline/librarian-chef
https://github.com/rodjek/librarian-puppet

:+1:
